### PR TITLE
Update to upstream changes in simple planner

### LINKED ISSUE #3: Update to changes in tesseract_planning simple planner
The API has changed for the simple motion planners, breaking the Python build. The SWIG interface needs to be updated to match.

### PR DESCRIPTION
**Pull request by johnwason**
This PR fixes #3

@Levi-Armstrong do you want to review before I merge?

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
Are the tests failing because of tcmalloc?

**Comment by johnwason** [comment]
Yeah Python segfaults if it is linked into the module. I made a PR to remove it from the library public interface.

**Comment by johnwason** [comment]
I am getting the error:

    /root/target_ws/install/setup.bash: line 11: COLCON_TRACE: unbound variable

during the CI builds

**Comment by johnwason** [comment]
I am going to merge this in, we can fix the CI later.

**Pull request merged**
